### ISSUE TITLE
On some servers, the user can execute flushdb.php.inc directly

### ISSUE THREAD

**Issue by mudrd8mz** [moodle-an-hochschulen/moodle-tool_redis#1]
Web server can be configured so that they handle the `*.php.inc` files as regular PHP files.

This file `lib/redis-stats/flushdb.php.inc` has no authentication and authorisation in it (other then checking the sesskey). As a result, an anonymous user can directly request URLs like

http://moodle.school.net/admin/tool/redis/lib/redis-stats/flushdb.php.inc?id=abcdef12345&s=0&db=0&async=0

and it would flush the redis database. This represents a possible performace degradation attack surface.

**Comment by mudrd8mz** [comment]
One solution might be to wrap the upstream files with functions, and call these functions.

**Comment by mudrd8mz** [comment]
Especially as you are modifying them already anyway (to add the `sesskey()` there).

**Comment by abias** [comment]
Thank you, @mudrd8mz , for highlighting this issue during the approval review.
I especially noted that you mentioned on https://tracker.moodle.org/browse/CONTRIB-8088?focusedCommentId=797697&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-797697 that I could have better used the redis-stats code as basis for own Moodle-specific code.

The fact that I went the way to include the existing tool redis-stats anyway leads to things like you are reporting here now. It's fair to highlight this downside.

On https://github.com/moodleuulm/moodle-tool_redis#security-note, we have already a security note about that fact saying:

> The Redis management GUI was added as a library to this Moodle plugin and was renamed to /lib/redis-gui/redis.php.inc.
> 
> There is a potential for sensitive data leak, not personal data but data about the webserver's PHP configuration, if your webserver is configured to interpret *.inc files as PHP. An anonymous user could then visit the library's index page directly via https://yourmoodle.com/admin/tool/redis/lib/redis-gui/redis.php.inc and would see the Redis management GUI circumventing Moodle's access control.
> 
> Please make sure that your webserver does not interpret *.inc files as PHP (which should be the default) or take any other measure that this file can not be accessed directly by a browser.

I have enhances this now to highlight the risk of flushing the DB in https://github.com/moodleuulm/moodle-tool_redis/commit/4cf6f94c73636eefa3ab2991a145b2075276047e

> The Redis management GUI was added as a library to this Moodle plugin and the library files were renamed to /lib/redis-gui/redis.php.inc and /lib/redis-gui/flushdb.php.inc.
> 
> There is a potential for sensitive data leak, not personal data but data about the webserver's PHP configuration, if your webserver is configured to interpret *.inc files as PHP. An anonymous user could then visit the library's index page directly via https://yourmoodle.com/admin/tool/redis/lib/redis-gui/redis.php.inc and would see the Redis management GUI circumventing Moodle's access control.
> 
> Similarly, there is also a potential for a performance degradation attack if your webserver is configured to interpret *.inc files as PHP. An anonymous user could then visit the library's flush page directly via https://yourmoodle.com/admin/tool/redis/lib/redis-gui/flushdb.php.inc with appropriate parameters and would flush the Redis DB circumventing Moodle's access control.
> 
> Please make sure that your webserver does not interpret *.inc files as PHP (which should be the default) or take any other measure that this file can not be accessed directly by a browser.

I also added the link to this note to the "Potential privacy issues" section on https://moodle.org/plugins/tool_redis

I think this should be fine as an intermediate solution and it's up to the sensitized admin to take care of hardening his system.

In a future version of this plugin, we might do it better by writing Moodle-native code directly.

Cheers,
Alex
