### ISSUE TITLE
Hardcoded admin directory in paths

### ISSUE THREAD

**Issue by adamtppaw** [moodle-an-hochschulen/moodle-tool_redis#2]
Hi, 
admin directory shouldn't be hardcoded in filepaths.  
It makes a problem when $CFG->admin is different then default 'admin'

So, whenever you need  
... /admin/.... 
you should use .../{$CFG->admin}/..

To reproduce issue:
1. rename admin directory to ie. bestadmin
2. change in config.php value $CFG->admin='admin'  to $CFG->admin='bestadmin'
3. Go to Redis panel in admin tab.

Adam

**Comment by abias** [comment]
Thank you @adamtppaw for highlighting this issue!
This is now fixed on https://github.com/moodleuulm/moodle-tool_redis/commit/00996f6bbaea68446d7a42bc1a58de86a8a2e6a2.

Cheers,
Alex
