### ISSUE TITLE
How does it work with moodle and redis in separate  docker containers?

### ISSUE THREAD

**Issue by moorthi07** [moodle-an-hochschulen/moodle-tool_redis#6]
I'm using moodle and redis on separate docker  containers and tried but not right. 
How can I make this tool make it work outside container or outside server redis cache?!

**Comment by abias** [comment]
This tool just re-uses the same connection to Redis which is configured in Moodle as cache store.
This should work without problems even if Redis is running in a different container.
The only thing I can imagine is that you might be using Redis just as session store. In this case, this (rather simple) tool most probably will not work at the moment. Sorry for that...
